folder: 'datafiles'

pos_files:
  - 'finalpos1819.xlsx'

dreg_files:
  - 'dreg.xlsx'

aliases:
  - file: "aliases.xlsx"
    key_col: "FINAL MC"
    new_col: "CORE CUSTOMER"

# merge:
#  - file: "product_hierarchy.xlsx"
#    pos_file_key: 'SALES PRODUCT'
#    merge_file_key: 'Ispn'
#    merge_res_key: 'ParentHierarchyNodeName'
#    new_col: 'Product Hierarchy'

drill_down_by:
  - 'DISTRIBUTOR'
  - 'FINAL MC'
  - 'CORE CUSTOMER'
  - 'COUNTRY FC'
  - 'DIV'
  - 'PL'
  - 'HFG'
  - 'SALES PRODUCT'
  - 'PRODUCT CLASS'

sum_by: 'POS FY'

crop_data:
  - col_name: 'CORE CUSTOMER'
    sum_by: 'POS FY'
    less_then: 50000.0
    replace_with: 'CUSTOMERS <50K EUR'
  - col_name: 'SALES PRODUCT'
    sum_by: 'POS FY'
    less_then: 10000.0
    replace_with: 'PRODUCTS <10K EUR'


number_format:
  divider: 1000.0
  format: '{:1.0f}'
  ending: ' K'

sort_param:
  top_n: 1000
  min: 0

display_elements:
    - name: 'something'
      type: 'table'
      columns:
        - 'customer'
        - 'part number'
        - 'value'
        - 'date'

# pages:
#  - name: 'blabla'
#    title: 'NKNKN'
#    elements:
#      - 'something'
#        position: 123


