
common:
  folder: 'datafiles'

  pos_files:
    - 'testpos_short.xlsx'
#    - 'finalpos1819.xlsx'

  dreg_files:
    - 'dreg.xlsx'

  crop_data:
    - col_name: 'CORE CUSTOMER'
      sum_by: 'POS FY'
      less_then: 50000.0
      replace_with: 'CUSTOMERS <50K EUR'
    - col_name: 'SALES PRODUCT'
      sum_by: 'POS FY'
      less_then: 10000.0
      replace_with: 'PRODUCTS <10K EUR'

  aliases:
    - file: "aliases.xlsx"
      key_col: "FINAL MC"
      new_col: "CORE CUSTOMER"

# merge:
#  - file: "product_hierarchy.xlsx"
#    pos_file_key: 'SALES PRODUCT'
#    merge_file_key: 'Ispn'
#    merge_res_key: 'ParentHierarchyNodeName'
#    new_col: 'Product Hierarchy'

views:
  - name: 'number tree'

    template: 'templ.html'
    structure: 'tree'

    drill_down_by:
      - 'DISTRIBUTOR'
      - 'FINAL MC'
      - 'CORE CUSTOMER'
      - 'COUNTRY FC'
      - 'DIV'
      - 'PL'
      - 'HFG'
      - 'SALES PRODUCT'
      - 'PRODUCT CLASS'

    sum_by: 'POS FY'

    number_format:
      divider: 1000.0
      format: '{:1.0f}'
      ending: ' K'

    sort_param:
      top_n: 1000
      min: 0

  - name: 'table tree'

    template: 'templ.html'
    structure: 'table_tree'

    drill_down_by:
      - 'DISTRIBUTOR'
      - 'FINAL MC'
      - 'CORE CUSTOMER'
      - 'COUNTRY FC'
      - 'DIV'
      - 'PL'
      - 'HFG'
      - 'SALES PRODUCT'
      - 'PRODUCT CLASS'

    sum_columns:
      - 'POS Q1-1'
      - 'POS Q2-1'
      - 'POS Q3-1'
      - 'POS Q4-1'
      - 'POS FY-1'
      - 'POS Q1'
      - 'POS Q2'
      - 'POS Q3'
      - 'POS Q4'
      - 'POS FY'

    sum_by: 'SUM'

    expand_by_1: 'DISTRIBUTOR'
    expand_by_2: 'time_period'

    number_format:
      divider: 1000.0
      format: '{:1.0f}'
      ending: ' K'

    sort_param:
      top_n: 1000
      min: 0
